# ----------- CONFIGURABLE START -----------
title:            "Hiếu.IO blog"
description:      "Bát nhã tâm kinh。"
url:              https://hieuio.github.io # 
signoff:          "HieuIO" # Your name
facebook_appid:   #liberxue
google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         Nhà
    url:          /
    external:     false
  - name:         Sống
    url:          /book
    external:     false
  - name:         Sách
    url:          /road
    external:     false
  - name:         Việc
    url:          /archives
    external:     false
  - name:         Vui
    url:          /tags
    external:     false
  - name:         Yêu
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
